'use client';
import Loading from '@/components/Loading';
import { useAppContext } from '@/context/AppContext';
import axios from 'axios';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';

export default function EquipmentPage() {
    const { getToken, user } = useAppContext();
    const [units, setUnits] = useState(null);
    const [products, setProducts] = useState([]);
    const [form, setForm] = useState({ product: '', serialNumber: '', condition: 'good', notes: '' });
    const [saving, setSaving] = useState(false);
    const load = async () => { const token = await getToken(); const [unitResponse, productResponse] = await Promise.all([axios.get('/api/equipment-units', { headers: { Authorization: `Bearer ${token}` } }), axios.get('/api/product/seller-list', { headers: { Authorization: `Bearer ${token}` } })]); setUnits(unitResponse.data.units); setProducts(productResponse.data.products || []); };
    useEffect(() => { if (user) load().catch(() => toast.error('Failed to load equipment')); }, [user]);
    const create = async e => { e.preventDefault(); setSaving(true); try { const token = await getToken(); await axios.post('/api/equipment-units', form, { headers: { Authorization: `Bearer ${token}` } }); setForm({ product: '', serialNumber: '', condition: 'good', notes: '' }); await load(); toast.success('Equipment unit created'); } catch (error) { toast.error(error.response?.data?.message || 'Failed to create unit'); } finally { setSaving(false); } };
    const update = async (unit, status, condition) => { try { const token = await getToken(); await axios.put(`/api/equipment-units/${unit._id}`, { status, condition, notes: unit.notes }, { headers: { Authorization: `Bearer ${token}` } }); await load(); toast.success('Unit updated'); } catch (error) { toast.error(error.response?.data?.message || 'Failed to update unit'); } };
    if (!units) return <Loading />;
    return <div className="p-6 w-full"><h1 className="text-2xl font-semibold">Equipment-unit tracking</h1><form onSubmit={create} className="grid md:grid-cols-5 gap-3 my-6 p-4 border rounded-lg bg-white"><select required value={form.product} onChange={e => setForm({ ...form, product: e.target.value })} className="border rounded p-2"><option value="">Select product</option>{products.map(product => <option key={product._id} value={product._id}>{product.name}</option>)}</select><input required maxLength="100" value={form.serialNumber} onChange={e => setForm({ ...form, serialNumber: e.target.value })} className="border rounded p-2" placeholder="Serial / asset number" /><select value={form.condition} onChange={e => setForm({ ...form, condition: e.target.value })} className="border rounded p-2"><option value="excellent">Excellent</option><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option></select><input value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} className="border rounded p-2" placeholder="Notes" /><button disabled={saving} className="bg-green-600 text-white rounded p-2 disabled:opacity-50">Add unit</button></form>
        <div className="overflow-x-auto border rounded-lg bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Serial</th><th className="p-3 text-left">Product</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Condition</th><th className="p-3 text-left">Current order</th><th className="p-3 text-left">Actions</th></tr></thead><tbody>{units.map(unit => <tr key={unit._id} className="border-t"><td className="p-3 font-mono">{unit.serialNumber}</td><td className="p-3">{unit.product?.name || 'Deleted product'}</td><td className="p-3">{unit.status}</td><td className="p-3">{unit.condition}</td><td className="p-3 font-mono">{unit.currentOrder?.slice(-8) || '—'}</td><td className="p-3"><select disabled={Boolean(unit.currentOrder)} value={unit.status} onChange={e => update(unit, e.target.value, e.target.value === 'damaged' ? 'damaged' : e.target.value === 'lost' ? 'lost' : unit.condition === 'damaged' || unit.condition === 'lost' ? 'good' : unit.condition)} className="border rounded p-1 disabled:bg-gray-100"><option value="available">Available</option><option value="damaged">Damaged</option><option value="lost">Lost</option><option value="retired">Retired</option></select></td></tr>)}{!units.length && <tr><td colSpan="6" className="p-8 text-center text-gray-500">No serialized units yet.</td></tr>}</tbody></table></div>
    </div>;
}
